### ISSUE TITLE
Executing Boolmutation python file

### ISSUE THREAD

**Issue by priyambial123** [lujunyan1118/SimpleBool#1]
Hi,
 I have been trying Boolean modeling of  protein interactions using SimpleBool. I imported the mutation.in txt file in canopy editor 
[mutation_in.txt](https://github.com/lujunyan1118/SimpleBool/files/511094/mutation_in.txt)

and tried executing Boolmutation.py script. I got the following error :
## %run "/home/JPJ/Priya_Ph.D/simple_bool/simplebool/SimpleBool-master/BoolMutation.py"

IOError                                   Traceback (most recent call last)
/home/JPJ/Priya_Ph.D/simple_bool/simplebool/SimpleBool-master/BoolMutation.py in <module>()
    383         para=ParaParser(sys.argv[1])
    384     except:
--> 385         para=ParaParser('mutation.in')
    386     simu_mutation(para)

/home/JPJ/Priya_Ph.D/simple_bool/simplebool/SimpleBool-master/BoolMutation.py in ParaParser(ParaFile)
    254             }  # define parameters
    255
--> 256     for each_line in open(ParaFile).readlines():
    257         para_name = each_line.split('=')[0].strip()
    258         para_value = each_line.split('=')[1].strip()

IOError: [Errno 2] No such file or directory: 'mutation.in'

Does this mean that the mutation.in.txt file has not been imported or the file should be a python file or I have not specified the directory properly?. I am new to Python and I am learning it. Kindly help me  to sort this issue, it would be of great help. I have attached the files that I have used.Pls find it

Thank you
Regards
Priya

**Comment by lujunyan1118** [comment]
Hi Priya,

Thanks for your message.  According to the error message, I think the input file name is wrong. It should be "mutation.in", not "mutation_in.txt".   Alternatively, you can run the script in command line. Then you can use any name you want for the input file.  like " python BoolMutation.py mutation_in.txt".  Hope it helps.

Regards,

Junyan

**Comment by priyambial123** [comment]
Thank you Junyan. Now the script is working
Regards
Priya

**Comment by priyambial123** [comment]
Hi,
    I could run the Boolmutation.py file and I also got the results saved in a csv file. But I got the following error message:
Write mutation result to 'mutation_result.csv' 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/home/JPJ/Priya_Ph.D/simple_bool/simplebool/SimpleBool-master/BoolMutation.py in <module>()
    385         para=ParaParser('mutation.in')
    386     simu_mutation(para)
--> 387 parser.add_argument('/home/JPJ/Priya_Ph.D/simple_bool/simplebool/SimpleBool-master/examples', default=os.getcwd())

NameError: name 'parser' is not defined 

What does this error mean? I have one more doubt, how were the values computed that contain the perturbed nodes with corresponding values. Were the values computed by Markov chain simulation?
Regards
Priya

**Comment by priyambial123** [comment]
Hi,
   I could not run the BoolAttractor.py file. I got this error message: %run "/home/JPJ/Priya_Ph.D/simple_bool/simplebool/SimpleBool-master/BoolAttractor.py"
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/JPJ/Priya_Ph.D/simple_bool/simplebool/SimpleBool-master/BoolAttractor.py in <module>()
    534 
    535 if __name__ == '__main__':
--> 536     if sys.argv[1]:
    537         para_file=sys.argv[1]
    538     else:

IndexError: list index out of range 

Pls help me with this issue. I have attached the steady.in and rules (migration1) text files. Pls find it
Thanks
Regards
Priya

[migration1.txt](https://github.com/lujunyan1118/SimpleBool/files/530776/migration1.txt)
[steady.in.txt](https://github.com/lujunyan1118/SimpleBool/files/530777/steady.in.txt)
